name: Upload to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install WASM dependencies
        run: |
          cargo install trunk --verbose
          rustup target add wasm32-unknown-unknown

      - name: Build website
        run: trunk build --verbose

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist