name: Upload to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pnpm
        run: npm install -g pnpm --verbose

      - name: Install dependencies
        run: pnpm install --verbose

      - name: Build website
        run: pnpm build --verbose

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
